import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import tw, { css, styled } from 'twin.macro'
import Modal from '../components/Modal'
import Tooltip from '../components/Tooltip'
import { useModal } from '../lib/useModal'

const TitleStyles = styled.h2`
   ${tw`text-gray-400 font-pb`}
`

const Home: NextPage = () => {
   const { isOpen, closeModal, openModal } = useModal()

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className={'padding'}>
            <h1 css={tw`text-red-600`}>Hello there!</h1>
            <TitleStyles>Hello</TitleStyles>

            <div>
               <h1 css={tw`font-pb text-3xl`}>Modal</h1>
               <button onClick={openModal}>Open modal</button>
            </div>

            <Tooltip content="Tooltip is here" placement="right">
               <span className="text-red-500 font-pb">Hover me</span>
            </Tooltip>

            <div>
               <Link href="/about">About</Link>
            </div>

            <Modal isOpen={isOpen} closeModal={closeModal}>
               Super modal window
            </Modal>
         </div>
      </>
   )
}

export default Home
